### ISSUE TITLE
Define database constraints in your migrations to keep integrity of data.

### ISSUE THREAD

**Issue by edwinthinks** [CamiMeneses/Cine#1]
One of the most important things in an application is the 'data integrity'. We need to build ways to ensure our data always makes sense. So that it won't save data that is incomplete or invalid.  

For example, imagine you have a model/table called `addresses` and someone is trying to save an address without the `city`. The address doesn't make sense without the `city` because the address could be anywhere! Hence you don't want to permit users from adding `addresses` that are confusing or incomplete.

This is where validations and database constraints come in. These two try to achieve the same thing but are different. I'll explain why you want to use database constraints first as a priority.

## Validations (Application Level)

https://guides.rubyonrails.org/active_record_validations.html
You may see validations like this in a Rails model:

```
class Event < ApplicationRecord
   validates_presence_of :date
end
```

These types of validations are application level. They live and run in your rails code. You would likely run into an issue if you did this `Event.last.update(date: nil)` with that validation defined. However, if you did `Event.last.update_column(:date, nil)` -- it would work. Why? Because you are able to skip validations defined in Rails. A developer that uses `update_column` will just ignore your validations and could introduce confusing data into your database.

A solution to this is database constraints.

## Database Constraints

These constraints are much more secure because it doesn't live in your application. It lives inside your database. If you called `Event.last.update_column(:date, nil)` when you have defined a NOT NULL constraint in your database, it will not work and raise an error. Good, we want that!

In your next migration, you can add database constraints like this:
```
class AddNullConstraintOnEventDate < ActiveRecord::Migration[5.1]
  def change
     change_column_null :events, :date, false
  end
end
``` 

There are several types of database constraints. You can see more here - https://edgeguides.rubyonrails.org/active_record_migrations.html. 

I'd recommend looking at foreign key constraints to ensure references between records are kept -https://edgeguides.rubyonrails.org/active_record_migrations.html#foreign-keys 

Let me know if you have any questions.

**Comment by edwinthinks** [comment]
👍 looks good. I would be cautious not to add `null` constraints if it isn't 100% necessary.

The foreign key constraint issue is related to the database you are using. SQLite isn't meant for production work and misses out on some features. Most projects I've seen utilize Postgres in production and locally. I'd suggest switching it to Postgres for this project and the next one :)

**Comment by CamiMeneses** [comment]
Thank you Edwin. Change the database to Postgres worked for me
